### ISSUE TITLE
Restructuring phase 2: Maintainers

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/meta#2]
This is the next phase of the restructuring outlined and approved in #1. This issue is dedicated to electing a single repsonsible maintainer for each repository. These rules decided on in #1 are particularly relevant:

* Every repository should have a single responsible maintainer.
* Maintainers volunteer, and are accepted if at least three (3) existing members agree. If there's multiple volunteers, and they all insist on it, the person with most "votes" win.
* Post-restructuring, the organization will be made up of only the maintainers. Other members will be removed.

To implement this, I propose that:
* Each volunteer posts a separate comment for each repository they are volunteering for, in the form "Vounteering for &lt;repository&gt;".
* Existing members approve these by giving them a thumbs up.
* Once approved by at least three existing members, I will add them to the list below.

If within a reasonable amount of time no-one volunteers to maintain a repository, they could perhaps be archived or moved out to another org like `reasonml-orphans`. We'll figure that out when the time comes.

Edit: If you find that someone else has volunteered to maintain a repository you think you'd be better fit for, you might want to talk with them directly to see if they might agree. They probably will :)

Repository | Maintainer
--- | ---
belt |  @chenglou 
bs-cookie-parser | @ncthbrt 
bs-director
bs-discord.js | @rickyvetter 
bs-downshift | @emmenko 
bs-express | @ncthbrt 
bs-fetch | @glennsl
bs-glob | @glennsl
bs-history | @Jimexist 
bs-immutablejs | @chenglou 
bs-leaflet | @Jimexist 
bs-loader | @rrdelaney 
bs-mocha | @Risto-Stevcev 
bs-moment | @grsabreu 
bs-node | @ncthbrt 
bs-react-native | @arnarthor 
bs-react-test-renderer | @wyze 
bs-socket.io | @bsansouci 
bs-transit-js | @IwanKaramazow 
bs-webapi-incubator | @glennsl
error-message-improvement | @chenglou 
Mareo | @chenglou 
meta | @glennsl
reason-maze | @chenglou 
reason-react-example | @chenglou 
reason-react-hacker-news | @wyze
reason-scripts | @rrdelaney 
reductive | @rickyvetter

**Comment by glennsl** [comment]
Volunteering for bs-fetch

**Comment by glennsl** [comment]
Volunteering for bs-glob

**Comment by glennsl** [comment]
Volunteering for bs-webapi-incubator

**Comment by glennsl** [comment]
Volunteering for meta

**Comment by ncthbrt** [comment]
Volunteering for bs-express and bs-node

**Comment by glennsl** [comment]
@ncthbrt Could you make it one comment per repository? It'd be easier to vote on it that way :)

**Comment by ncthbrt** [comment]
Volunteering for bs-node

**Comment by ncthbrt** [comment]
@glennsl Feels like meta should be excluded from this process because it isn't a project in the traditional sense.

**Comment by glennsl** [comment]
Thanks!

`meta` still has to have someone to respond to requests, keep information "owned" elsewhere up to date, like the maintainers list, and make (trivial) "design" decisions like how to format the readme. It could be a collective responsibility, but it seems simpler and in my experience works better to have a single person responsible. That still doesn't mean that this single person should do everything, of course.

Btw, In my more complete proposal I've assigned the role of maintaining `meta` as well as cross-repository coordination and such to an "Administrator". But we're not there yet.

**Comment by arnarthor** [comment]
Volunteering for bs-react-native

**Comment by emmenko** [comment]
Vounteering for `bs-downshift`

**Comment by grsabreu** [comment]
Volunteering for bs-moment

**Comment by rrdelaney** [comment]
bs-loader

**Comment by rrdelaney** [comment]
react-scripts

**Comment by bsansouci** [comment]
bs-socket.io

**Comment by glennsl** [comment]
@rrdelaney I assume you mean `reason-scripts`? 😆

**Comment by rrdelaney** [comment]
@glennsl yea, updated the comment 😅

**Comment by rrdelaney** [comment]
@glennsl Should we make a "maintainers" team and use [GH discussions](https://github.com/blog/2471-introducing-team-discussions) for this?

**Comment by glennsl** [comment]
@rrdelaney Personally I'd prefer to keep everything in the open. Otherwise not sure what the benefits are compared to just using issues or Discord?

**Comment by rrdelaney** [comment]
I think you can mark threads as public, the benefit is we don’t need a “meta” repo to discuss things

**Comment by glennsl** [comment]
It seems public only means for members of the organization, vs just team members:

> All organization members can see your discussion posts by default. Mark your post as private if you have something more sensitive to share.

I also think the `meta` repo will be necessarry for organization-wide information anyway, such as what the organizations purpose is, and the process for donating a repository, becoming a maintainer and member etc.

**Comment by chenglou** [comment]
bs-immutablejs, reason-maze, Mareo, reason-react-example, error-message-improvement

**Comment by rrdelaney** [comment]
@glennsl oh my bad yea, I thought public would be public to anyone,  it just group members. 

Sounds good to keep meta then 😁

**Comment by rickyvetter** [comment]
Volunteering for bs-discord.js

**Comment by rickyvetter** [comment]
Volunteering for reductive

**Comment by ncthbrt** [comment]
Volunteering for bs-cookie-parser

**Comment by Risto-Stevcev** [comment]
volunteering for bs-mocha

**Comment by wyze** [comment]
Volunteering for `bs-react-test-renderer`

**Comment by IwanKaramazow** [comment]
Volunteering for `bs-transit-js`

**Comment by Jimexist** [comment]
Volunteering for `bs-moment` and `bs-leaflet`

**Comment by ncthbrt** [comment]
@Jimexist As @glennsl said earlier, mind one comment per repo?

**Comment by Jimexist** [comment]
Volunteering for `bs-leaflet`

**Comment by mobily** [comment]
@glennsl just to be clear, I agree with the rules, but for example, the `bs-react-native` repo is huge, do you think one maintainer is enough?

**Comment by glennsl** [comment]
@mobily I don't, and I addressed that [here](https://github.com/reasonml-community/meta/issues/1#issuecomment-362001544). In short, it's about responsibility, not assignment. As the responsible maintainer, exactly _how_ you choose to keep the repository maintained is entirely up to you.

But this is also just my opinion, of course. It's not been clearly defined, but thisd was my intent when proposing it.

**Comment by Jimexist** [comment]
Volunteering for `bs-history`

**Comment by Jimexist** [comment]
@grsabreu I see that you are taking `bs-moment`. I don't have any problem about that. But I currently do publishing for the repo (and tried to do it frequent enough). I'm not sure how npm publishing will be migrated. If that's not troublesome then we should do that as well. Otherwise, I can still be managing the repo and reviewing PRs - if that's okay with you I can also cover the github repo maintenance as well.

**Comment by arnarthor** [comment]
@mobily I'm volunteering for bs-react-native, but I'm pretty sure that at least @wokalski will be an active maintainer as well and we have been getting a lot of community contributions from active members as well which have been really helpful. 

We accept whatever help we can get to maintain it 👍

**Comment by wokalski** [comment]
@glennsl what's the process if:

1. someone does a terrible job (or doesn't have time etc)
2. steps down as a maintainer

**Comment by glennsl** [comment]
@wokalski That's up to the organization, meaning the repsonsible maintainers, to decide collectively. You can read my thoughts on it [here](https://github.com/glennsl/reasonml-community-meta-proposal), specifically the process section should answer your questions pretty straightforwardly.

But from what has been decided on already (in #1), I think it follows that the maintainer would be responsible for finding their own replacement, which then needs to be approved by three existing members (two in addition to the current maintainer). The organization also has the power to decide on anything through an absolute majority vote, so if someone does a bad job and refuses to step down voluntarily, they could be forced out that way. Let's hope it doesn't ever go that far though :)

**Comment by wokalski** [comment]
@glennsl Cool, thank you.

Besides that, what does a `member` mean? If I understand correctly it's a member of the organisation, not a repo, right? I'm asking because of this one:

> Any member can add new members, but must get approval from at least two other existing members.

If member, means a person listed under collaborators in a repository, `bs-react-native` doesn't obey (and won't) this rule. We give every contributor write permissions to the repository which helps us maintain it.

**Comment by mobily** [comment]
@glennsl @arnarthor thanks for the feedback, I want to help as much as I can 😉

**Comment by glennsl** [comment]
@wokalski Yes, "member" means a member of the organization, which is defined as the set of current responsible maintainers of repositories managed by the organization. There's no concept of a "member" that relates to repositories in my writing (I hope), and there's no such concept in GitHub terminology either I think. I also don't see a need for the organization to meddle in how each repository organizes itself, unless it defies the purpose of the organization.

Don't read too much into my rambling thoughts though :) I just stared writing things down, and didn't intend to make it a proper proposal until I'd thought about it a whole lot more.

**Comment by glennsl** [comment]
Status

Repository | Status
--- | ---
belt | No volunteer, will probably be moved or obsoleted soon
bs-director | No volunteer. Still actively used, so would be nice to have it maintained.
bs-downshift | [@emmenko volunteered, is original author, missing votes](https://github.com/reasonml-community/meta/issues/2#issuecomment-363063510)
bs-examples | No volunteer, doesn't serve much of a purpose so I suggest archiving
bs-history | [@Jimexist volunteered, is original author, missing votes](https://github.com/reasonml-community/meta/issues/2#issuecomment-364079138)
bs-leaflet | [@Jimexist volunteered, is original author, missing votes](https://github.com/reasonml-community/meta/issues/2#issuecomment-364040919)
reason-react-hacker-news | No volunteer. but I can take it on if noone else wants it

Please consider voting on or volunteering for any of these.

If in a day or two there's still repositories without maintainers, we have to decide what to do with them. The choices I see are:

* Archiving
* Marking clearly as `[UNMAINTAINED]`
* Moving to another org, such as `reasonml-orphans`

**Comment by grsabreu** [comment]
thanks a good point @Jimexist, I think you can take care of the publishing  for now, I can take care of reviewing and maintaining also with you

**Comment by wyze** [comment]
I wasn't sure if `reason-react-hacker-news` was something that you wanted carried forward so I didn't volunteer. Also, not sure if my votes count because I'm not a current member, so I didn't vote on anything. :)

**Comment by wyze** [comment]
Volunteering for `reason-react-hacker-news`.

**Comment by glennsl** [comment]
@wyze My understanding is it wouldn't count, but it wouldn't be a disaster if you did vote. I'd just not count it :)

Also, what I want isn't very important, but reason-react-hacker-news seems like one of the better app examples and a good one to keep maintained. So thanks! :)

**Comment by chenglou** [comment]
Taking on Belt (the issues repo. Actually code in BS).

**Comment by glennsl** [comment]
We now have maintainers for all repositories except `bs-director`, which has been marked as `[UNMAINTAINED]` to try to subtly get that point across. We've also moved the archived repostiories, as well as `bs-examples` to `reasonml-old`.

In addition, Phase 3: The Great Purge, has been completed. 11 previous members have been removed and the new maintainers that were not already members have been sent invites. Please let me know if I've screwed something up though. I'm sure I have somehow.

And please look over the repositories you're now repsonsible for to make sure they're up-to-date, and that only the people that should have commit access actually do. Also make sure you have the necessary publishing rights on npm.
